// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package serialization

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobRequest struct {
	Type      string       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Remark    string       `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Training  *JobTraining `protobuf:"bytes,3,opt,name=training,proto3" json:"training,omitempty"`
	Priority  float64      `protobuf:"fixed64,4,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt string       `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CreatedBy string       `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	Name      string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Target    string       `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	// maximum executing time for the training batchv1.Job
	ActiveDeadlineSeconds uint64 `protobuf:"varint,9,opt,name=activeDeadlineSeconds,proto3" json:"activeDeadlineSeconds,omitempty"`
	// the planning start time in RFC3339
	ScheduledAt          string   `protobuf:"bytes,10,opt,name=scheduledAt,proto3" json:"scheduledAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JobRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *JobRequest) GetTraining() *JobTraining {
	if m != nil {
		return m.Training
	}
	return nil
}

func (m *JobRequest) GetPriority() float64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *JobRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *JobRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *JobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *JobRequest) GetActiveDeadlineSeconds() uint64 {
	if m != nil {
		return m.ActiveDeadlineSeconds
	}
	return 0
}

func (m *JobRequest) GetScheduledAt() string {
	if m != nil {
		return m.ScheduledAt
	}
	return ""
}

type JobTraining struct {
	// specify the training type (can be "predefined" or "custom")
	Type        string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Application string               `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	Resources   map[string]*Resource `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Workspace   *JobWorkspace        `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// when the build config is specified, we will add steps to build a docker
	// image in the cluster.
	BuildConfig *JobBuildConfig `protobuf:"bytes,6,opt,name=buildConfig,proto3" json:"buildConfig,omitempty"`
	// when container is specified, a container will be built with the
	// information.
	Containers []*Container `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	Finalizers []*Container `protobuf:"bytes,8,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	// training config is a JSON string
	JsonConfig           string   `protobuf:"bytes,9,opt,name=jsonConfig,proto3" json:"jsonConfig,omitempty"`
	Model                string   `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobTraining) Reset()         { *m = JobTraining{} }
func (m *JobTraining) String() string { return proto.CompactTextString(m) }
func (*JobTraining) ProtoMessage()    {}
func (*JobTraining) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *JobTraining) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobTraining.Unmarshal(m, b)
}
func (m *JobTraining) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobTraining.Marshal(b, m, deterministic)
}
func (m *JobTraining) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobTraining.Merge(m, src)
}
func (m *JobTraining) XXX_Size() int {
	return xxx_messageInfo_JobTraining.Size(m)
}
func (m *JobTraining) XXX_DiscardUnknown() {
	xxx_messageInfo_JobTraining.DiscardUnknown(m)
}

var xxx_messageInfo_JobTraining proto.InternalMessageInfo

func (m *JobTraining) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *JobTraining) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *JobTraining) GetResources() map[string]*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *JobTraining) GetWorkspace() *JobWorkspace {
	if m != nil {
		return m.Workspace
	}
	return nil
}

func (m *JobTraining) GetBuildConfig() *JobBuildConfig {
	if m != nil {
		return m.BuildConfig
	}
	return nil
}

func (m *JobTraining) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *JobTraining) GetFinalizers() []*Container {
	if m != nil {
		return m.Finalizers
	}
	return nil
}

func (m *JobTraining) GetJsonConfig() string {
	if m != nil {
		return m.JsonConfig
	}
	return ""
}

func (m *JobTraining) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

// JobBuildConfig is used for building the docker image from the jupyter notebook
type JobBuildConfig struct {
	From           string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Tag            string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	File           string `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Entrypoint     string `protobuf:"bytes,4,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	RegistryServer string `protobuf:"bytes,5,opt,name=registryServer,proto3" json:"registryServer,omitempty"`
	// runtime fields
	Args                 []string       `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Env                  []*EnvVar      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty"`
	TrainingLogPath      string         `protobuf:"bytes,8,opt,name=trainingLogPath,proto3" json:"trainingLogPath,omitempty"`
	ModelArtifact        *ModelArtifact `protobuf:"bytes,9,opt,name=modelArtifact,proto3" json:"modelArtifact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JobBuildConfig) Reset()         { *m = JobBuildConfig{} }
func (m *JobBuildConfig) String() string { return proto.CompactTextString(m) }
func (*JobBuildConfig) ProtoMessage()    {}
func (*JobBuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *JobBuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobBuildConfig.Unmarshal(m, b)
}
func (m *JobBuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobBuildConfig.Marshal(b, m, deterministic)
}
func (m *JobBuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobBuildConfig.Merge(m, src)
}
func (m *JobBuildConfig) XXX_Size() int {
	return xxx_messageInfo_JobBuildConfig.Size(m)
}
func (m *JobBuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_JobBuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_JobBuildConfig proto.InternalMessageInfo

func (m *JobBuildConfig) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *JobBuildConfig) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *JobBuildConfig) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *JobBuildConfig) GetEntrypoint() string {
	if m != nil {
		return m.Entrypoint
	}
	return ""
}

func (m *JobBuildConfig) GetRegistryServer() string {
	if m != nil {
		return m.RegistryServer
	}
	return ""
}

func (m *JobBuildConfig) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *JobBuildConfig) GetEnv() []*EnvVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *JobBuildConfig) GetTrainingLogPath() string {
	if m != nil {
		return m.TrainingLogPath
	}
	return ""
}

func (m *JobBuildConfig) GetModelArtifact() *ModelArtifact {
	if m != nil {
		return m.ModelArtifact
	}
	return nil
}

type ModelArtifact struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	CheckpointDir        string   `protobuf:"bytes,2,opt,name=checkpointDir,proto3" json:"checkpointDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelArtifact) Reset()         { *m = ModelArtifact{} }
func (m *ModelArtifact) String() string { return proto.CompactTextString(m) }
func (*ModelArtifact) ProtoMessage()    {}
func (*ModelArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *ModelArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelArtifact.Unmarshal(m, b)
}
func (m *ModelArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelArtifact.Marshal(b, m, deterministic)
}
func (m *ModelArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelArtifact.Merge(m, src)
}
func (m *ModelArtifact) XXX_Size() int {
	return xxx_messageInfo_ModelArtifact.Size(m)
}
func (m *ModelArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_ModelArtifact proto.InternalMessageInfo

func (m *ModelArtifact) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ModelArtifact) GetCheckpointDir() string {
	if m != nil {
		return m.CheckpointDir
	}
	return ""
}

type Container struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string    `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command              []string  `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args                 []string  `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env                  []*EnvVar `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	WorkingDir           string    `protobuf:"bytes,6,opt,name=workingDir,proto3" json:"workingDir,omitempty"`
	ImagePullPolicy      string    `protobuf:"bytes,7,opt,name=imagePullPolicy,proto3" json:"imagePullPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{4}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Container) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Container) GetEnv() []*EnvVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Container) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *Container) GetImagePullPolicy() string {
	if m != nil {
		return m.ImagePullPolicy
	}
	return ""
}

type EnvVar struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvVar) Reset()         { *m = EnvVar{} }
func (m *EnvVar) String() string { return proto.CompactTextString(m) }
func (*EnvVar) ProtoMessage()    {}
func (*EnvVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{5}
}

func (m *EnvVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvVar.Unmarshal(m, b)
}
func (m *EnvVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvVar.Marshal(b, m, deterministic)
}
func (m *EnvVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvVar.Merge(m, src)
}
func (m *EnvVar) XXX_Size() int {
	return xxx_messageInfo_EnvVar.Size(m)
}
func (m *EnvVar) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvVar.DiscardUnknown(m)
}

var xxx_messageInfo_EnvVar proto.InternalMessageInfo

func (m *EnvVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type JobWorkspace struct {
	Load                 *JobWorkspace_BatchLoad   `protobuf:"bytes,1,opt,name=load,proto3" json:"load,omitempty"`
	Create               *JobWorkspace_BatchCreate `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	JpegQuality          float64                   `protobuf:"fixed64,3,opt,name=jpegQuality,proto3" json:"jpegQuality,omitempty"`
	Annotation           string                    `protobuf:"bytes,4,opt,name=annotation,proto3" json:"annotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JobWorkspace) Reset()         { *m = JobWorkspace{} }
func (m *JobWorkspace) String() string { return proto.CompactTextString(m) }
func (*JobWorkspace) ProtoMessage()    {}
func (*JobWorkspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{6}
}

func (m *JobWorkspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobWorkspace.Unmarshal(m, b)
}
func (m *JobWorkspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobWorkspace.Marshal(b, m, deterministic)
}
func (m *JobWorkspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobWorkspace.Merge(m, src)
}
func (m *JobWorkspace) XXX_Size() int {
	return xxx_messageInfo_JobWorkspace.Size(m)
}
func (m *JobWorkspace) XXX_DiscardUnknown() {
	xxx_messageInfo_JobWorkspace.DiscardUnknown(m)
}

var xxx_messageInfo_JobWorkspace proto.InternalMessageInfo

func (m *JobWorkspace) GetLoad() *JobWorkspace_BatchLoad {
	if m != nil {
		return m.Load
	}
	return nil
}

func (m *JobWorkspace) GetCreate() *JobWorkspace_BatchCreate {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *JobWorkspace) GetJpegQuality() float64 {
	if m != nil {
		return m.JpegQuality
	}
	return 0
}

func (m *JobWorkspace) GetAnnotation() string {
	if m != nil {
		return m.Annotation
	}
	return ""
}

type JobWorkspace_BatchCreate struct {
	DatasetIds           []string `protobuf:"bytes,1,rep,name=datasetIds,proto3" json:"datasetIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobWorkspace_BatchCreate) Reset()         { *m = JobWorkspace_BatchCreate{} }
func (m *JobWorkspace_BatchCreate) String() string { return proto.CompactTextString(m) }
func (*JobWorkspace_BatchCreate) ProtoMessage()    {}
func (*JobWorkspace_BatchCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{6, 0}
}

func (m *JobWorkspace_BatchCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobWorkspace_BatchCreate.Unmarshal(m, b)
}
func (m *JobWorkspace_BatchCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobWorkspace_BatchCreate.Marshal(b, m, deterministic)
}
func (m *JobWorkspace_BatchCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobWorkspace_BatchCreate.Merge(m, src)
}
func (m *JobWorkspace_BatchCreate) XXX_Size() int {
	return xxx_messageInfo_JobWorkspace_BatchCreate.Size(m)
}
func (m *JobWorkspace_BatchCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobWorkspace_BatchCreate.DiscardUnknown(m)
}

var xxx_messageInfo_JobWorkspace_BatchCreate proto.InternalMessageInfo

func (m *JobWorkspace_BatchCreate) GetDatasetIds() []string {
	if m != nil {
		return m.DatasetIds
	}
	return nil
}

type JobWorkspace_BatchLoad struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobWorkspace_BatchLoad) Reset()         { *m = JobWorkspace_BatchLoad{} }
func (m *JobWorkspace_BatchLoad) String() string { return proto.CompactTextString(m) }
func (*JobWorkspace_BatchLoad) ProtoMessage()    {}
func (*JobWorkspace_BatchLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{6, 1}
}

func (m *JobWorkspace_BatchLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobWorkspace_BatchLoad.Unmarshal(m, b)
}
func (m *JobWorkspace_BatchLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobWorkspace_BatchLoad.Marshal(b, m, deterministic)
}
func (m *JobWorkspace_BatchLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobWorkspace_BatchLoad.Merge(m, src)
}
func (m *JobWorkspace_BatchLoad) XXX_Size() int {
	return xxx_messageInfo_JobWorkspace_BatchLoad.Size(m)
}
func (m *JobWorkspace_BatchLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_JobWorkspace_BatchLoad.DiscardUnknown(m)
}

var xxx_messageInfo_JobWorkspace_BatchLoad proto.InternalMessageInfo

func (m *JobWorkspace_BatchLoad) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Kubernetes Resource Quotas https://kubernetes.io/docs/concepts/policy/resource-quotas/
type ResourceRequest struct {
	Cpu                  string   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem                  string   `protobuf:"bytes,2,opt,name=mem,proto3" json:"mem,omitempty"`
	Gpu                  string   `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Replica              uint32   `protobuf:"varint,4,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceRequest) Reset()         { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()    {}
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{7}
}

func (m *ResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequest.Unmarshal(m, b)
}
func (m *ResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequest.Marshal(b, m, deterministic)
}
func (m *ResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequest.Merge(m, src)
}
func (m *ResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceRequest.Size(m)
}
func (m *ResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequest proto.InternalMessageInfo

func (m *ResourceRequest) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *ResourceRequest) GetMem() string {
	if m != nil {
		return m.Mem
	}
	return ""
}

func (m *ResourceRequest) GetGpu() string {
	if m != nil {
		return m.Gpu
	}
	return ""
}

func (m *ResourceRequest) GetReplica() uint32 {
	if m != nil {
		return m.Replica
	}
	return 0
}

type Resource struct {
	Request              *ResourceRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Limit                *ResourceLimit   `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{8}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetRequest() *ResourceRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Resource) GetLimit() *ResourceLimit {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ResourceLimit struct {
	Cpu                  string   `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem                  string   `protobuf:"bytes,2,opt,name=mem,proto3" json:"mem,omitempty"`
	Gpu                  string   `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceLimit) Reset()         { *m = ResourceLimit{} }
func (m *ResourceLimit) String() string { return proto.CompactTextString(m) }
func (*ResourceLimit) ProtoMessage()    {}
func (*ResourceLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{9}
}

func (m *ResourceLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceLimit.Unmarshal(m, b)
}
func (m *ResourceLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceLimit.Marshal(b, m, deterministic)
}
func (m *ResourceLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceLimit.Merge(m, src)
}
func (m *ResourceLimit) XXX_Size() int {
	return xxx_messageInfo_ResourceLimit.Size(m)
}
func (m *ResourceLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceLimit.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceLimit proto.InternalMessageInfo

func (m *ResourceLimit) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *ResourceLimit) GetMem() string {
	if m != nil {
		return m.Mem
	}
	return ""
}

func (m *ResourceLimit) GetGpu() string {
	if m != nil {
		return m.Gpu
	}
	return ""
}

type JobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{10}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *JobResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type StopJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopJobRequest) Reset()         { *m = StopJobRequest{} }
func (m *StopJobRequest) String() string { return proto.CompactTextString(m) }
func (*StopJobRequest) ProtoMessage()    {}
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{11}
}

func (m *StopJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopJobRequest.Unmarshal(m, b)
}
func (m *StopJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopJobRequest.Marshal(b, m, deterministic)
}
func (m *StopJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopJobRequest.Merge(m, src)
}
func (m *StopJobRequest) XXX_Size() int {
	return xxx_messageInfo_StopJobRequest.Size(m)
}
func (m *StopJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopJobRequest proto.InternalMessageInfo

func (m *StopJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ChangePriorityRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Priority             float64  `protobuf:"fixed64,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePriorityRequest) Reset()         { *m = ChangePriorityRequest{} }
func (m *ChangePriorityRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePriorityRequest) ProtoMessage()    {}
func (*ChangePriorityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{12}
}

func (m *ChangePriorityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePriorityRequest.Unmarshal(m, b)
}
func (m *ChangePriorityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePriorityRequest.Marshal(b, m, deterministic)
}
func (m *ChangePriorityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePriorityRequest.Merge(m, src)
}
func (m *ChangePriorityRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePriorityRequest.Size(m)
}
func (m *ChangePriorityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePriorityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePriorityRequest proto.InternalMessageInfo

func (m *ChangePriorityRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangePriorityRequest) GetPriority() float64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type DeleteJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobRequest) Reset()         { *m = DeleteJobRequest{} }
func (m *DeleteJobRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJobRequest) ProtoMessage()    {}
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{13}
}

func (m *DeleteJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobRequest.Unmarshal(m, b)
}
func (m *DeleteJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobRequest.Merge(m, src)
}
func (m *DeleteJobRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJobRequest.Size(m)
}
func (m *DeleteJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobRequest proto.InternalMessageInfo

func (m *DeleteJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RerunJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RerunJobRequest) Reset()         { *m = RerunJobRequest{} }
func (m *RerunJobRequest) String() string { return proto.CompactTextString(m) }
func (*RerunJobRequest) ProtoMessage()    {}
func (*RerunJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{14}
}

func (m *RerunJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RerunJobRequest.Unmarshal(m, b)
}
func (m *RerunJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RerunJobRequest.Marshal(b, m, deterministic)
}
func (m *RerunJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RerunJobRequest.Merge(m, src)
}
func (m *RerunJobRequest) XXX_Size() int {
	return xxx_messageInfo_RerunJobRequest.Size(m)
}
func (m *RerunJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RerunJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RerunJobRequest proto.InternalMessageInfo

func (m *RerunJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*JobRequest)(nil), "serialization.JobRequest")
	proto.RegisterType((*JobTraining)(nil), "serialization.JobTraining")
	proto.RegisterMapType((map[string]*Resource)(nil), "serialization.JobTraining.ResourcesEntry")
	proto.RegisterType((*JobBuildConfig)(nil), "serialization.JobBuildConfig")
	proto.RegisterType((*ModelArtifact)(nil), "serialization.ModelArtifact")
	proto.RegisterType((*Container)(nil), "serialization.Container")
	proto.RegisterType((*EnvVar)(nil), "serialization.EnvVar")
	proto.RegisterType((*JobWorkspace)(nil), "serialization.JobWorkspace")
	proto.RegisterType((*JobWorkspace_BatchCreate)(nil), "serialization.JobWorkspace.BatchCreate")
	proto.RegisterType((*JobWorkspace_BatchLoad)(nil), "serialization.JobWorkspace.BatchLoad")
	proto.RegisterType((*ResourceRequest)(nil), "serialization.ResourceRequest")
	proto.RegisterType((*Resource)(nil), "serialization.Resource")
	proto.RegisterType((*ResourceLimit)(nil), "serialization.ResourceLimit")
	proto.RegisterType((*JobResponse)(nil), "serialization.JobResponse")
	proto.RegisterType((*StopJobRequest)(nil), "serialization.StopJobRequest")
	proto.RegisterType((*ChangePriorityRequest)(nil), "serialization.ChangePriorityRequest")
	proto.RegisterType((*DeleteJobRequest)(nil), "serialization.DeleteJobRequest")
	proto.RegisterType((*RerunJobRequest)(nil), "serialization.RerunJobRequest")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x72, 0xe4, 0x34,
	0x10, 0x66, 0x7e, 0x33, 0x6e, 0x33, 0xb3, 0x5b, 0xaa, 0x5d, 0x30, 0xb3, 0x21, 0x0c, 0xae, 0x85,
	0x1d, 0x0e, 0x9b, 0xc3, 0x40, 0x51, 0x59, 0x2e, 0x5b, 0x3b, 0x49, 0xf8, 0x49, 0x85, 0x22, 0xab,
	0x2c, 0x50, 0xc5, 0x4d, 0x63, 0x2b, 0x8e, 0x12, 0x5b, 0xf2, 0xca, 0x72, 0x60, 0x38, 0x71, 0xe5,
	0x0d, 0x78, 0x19, 0xde, 0x80, 0x33, 0xcf, 0x43, 0x49, 0x96, 0x67, 0x6c, 0x27, 0x93, 0xa9, 0xe2,
	0xa6, 0x6e, 0x7d, 0xdd, 0xea, 0xfe, 0xd4, 0xdd, 0x12, 0x38, 0x57, 0x62, 0xb1, 0x9f, 0x4a, 0xa1,
	0x04, 0x1a, 0x66, 0x54, 0x32, 0x12, 0xb3, 0xdf, 0x89, 0x62, 0x82, 0xfb, 0xff, 0xb4, 0x01, 0x4e,
	0xc4, 0x02, 0xd3, 0xb7, 0x39, 0xcd, 0x14, 0x42, 0xd0, 0x55, 0xcb, 0x94, 0x7a, 0xad, 0x49, 0x6b,
	0xea, 0x60, 0xb3, 0x46, 0xef, 0x41, 0x5f, 0xd2, 0x84, 0xc8, 0x6b, 0xaf, 0x6d, 0xb4, 0x56, 0x42,
	0x5f, 0xc2, 0x40, 0x49, 0xc2, 0x38, 0xe3, 0x91, 0xd7, 0x99, 0xb4, 0xa6, 0xee, 0x6c, 0xbc, 0x5f,
	0x73, 0xbe, 0x7f, 0x22, 0x16, 0x6f, 0x2c, 0x02, 0xaf, 0xb0, 0x68, 0x0c, 0x83, 0x54, 0x32, 0x21,
	0x99, 0x5a, 0x7a, 0xdd, 0x49, 0x6b, 0xda, 0xc2, 0x2b, 0x19, 0xed, 0x82, 0x13, 0x48, 0x4a, 0x14,
	0x0d, 0x5f, 0x29, 0xaf, 0x67, 0x8e, 0x5b, 0x2b, 0x2a, 0xbb, 0xf3, 0xa5, 0xd7, 0xaf, 0xed, 0xce,
	0x97, 0x3a, 0x76, 0x4e, 0x12, 0xea, 0xed, 0x14, 0xb1, 0xeb, 0xb5, 0x8e, 0x5d, 0x11, 0x19, 0x51,
	0xe5, 0x0d, 0x8a, 0xd8, 0x0b, 0x09, 0x7d, 0x01, 0x8f, 0x49, 0xa0, 0xd8, 0x0d, 0x3d, 0xa2, 0x24,
	0x8c, 0x19, 0xa7, 0xe7, 0x34, 0x10, 0x3c, 0xcc, 0x3c, 0x67, 0xd2, 0x9a, 0x76, 0xf1, 0xdd, 0x9b,
	0x68, 0x02, 0x6e, 0x16, 0x5c, 0xd2, 0x30, 0x8f, 0x4d, 0x7c, 0x60, 0x5c, 0x56, 0x55, 0xfe, 0x9f,
	0x5d, 0x70, 0x2b, 0x59, 0xaf, 0xf8, 0x6c, 0x57, 0xf8, 0x9c, 0x80, 0x4b, 0xd2, 0x34, 0x66, 0x81,
	0x21, 0xc9, 0x50, 0xe7, 0xe0, 0xaa, 0x0a, 0x7d, 0x03, 0x8e, 0xa4, 0x99, 0xc8, 0x65, 0x40, 0x33,
	0xaf, 0x3b, 0xe9, 0x4c, 0xdd, 0xd9, 0x67, 0x9b, 0xa9, 0xdd, 0xc7, 0x25, 0xf6, 0x98, 0x2b, 0xb9,
	0xc4, 0x6b, 0x5b, 0xf4, 0x02, 0x9c, 0x5f, 0x85, 0xbc, 0xce, 0x52, 0x12, 0x50, 0x43, 0xa7, 0x3b,
	0x7b, 0x72, 0xdb, 0xd1, 0xcf, 0x25, 0x04, 0xaf, 0xd1, 0xe8, 0x25, 0xb8, 0x8b, 0x9c, 0xc5, 0xe1,
	0xa1, 0xe0, 0x17, 0x2c, 0x32, 0x6c, 0xbb, 0xb3, 0x0f, 0x6f, 0x1b, 0xcf, 0xd7, 0x20, 0x5c, 0xb5,
	0x40, 0x07, 0x00, 0x81, 0xe0, 0x8a, 0x30, 0x4e, 0x65, 0xe6, 0xed, 0x98, 0x2c, 0xbc, 0x86, 0xfd,
	0x61, 0x09, 0xc0, 0x15, 0xac, 0xb6, 0xbc, 0x60, 0x5c, 0xa3, 0xb4, 0xe5, 0x60, 0x9b, 0xe5, 0x1a,
	0x8b, 0xf6, 0x00, 0xae, 0x32, 0xc1, 0x6d, 0xcc, 0x8e, 0x61, 0xb6, 0xa2, 0x41, 0x8f, 0xa0, 0x97,
	0x88, 0x90, 0xc6, 0xf6, 0xea, 0x0a, 0x61, 0xfc, 0x23, 0x8c, 0xea, 0x14, 0xa2, 0x87, 0xd0, 0xb9,
	0xa6, 0x4b, 0xdb, 0x05, 0x7a, 0x89, 0x9e, 0x43, 0xef, 0x86, 0xc4, 0x79, 0x71, 0x93, 0xee, 0xec,
	0xfd, 0x46, 0x38, 0xa5, 0x3d, 0x2e, 0x50, 0x5f, 0xb5, 0x0f, 0x5a, 0xfe, 0xdf, 0x6d, 0x18, 0xd5,
	0x09, 0xd2, 0xe5, 0x70, 0x21, 0x45, 0x52, 0xb6, 0x97, 0x5e, 0xeb, 0xb3, 0x14, 0x89, 0x6c, 0x85,
	0xe8, 0xa5, 0x41, 0xb1, 0x98, 0xda, 0xca, 0x30, 0x6b, 0x9d, 0x19, 0xd5, 0xa1, 0xa5, 0x82, 0x71,
	0x65, 0xda, 0xc6, 0xc1, 0x15, 0x0d, 0xfa, 0x14, 0x46, 0x92, 0x46, 0x2c, 0x53, 0x72, 0x79, 0x4e,
	0xe5, 0x0d, 0x95, 0xb6, 0x7b, 0x1a, 0x5a, 0xed, 0x9b, 0xc8, 0x28, 0xf3, 0xfa, 0x93, 0x8e, 0xf6,
	0xad, 0xd7, 0xe8, 0x19, 0x74, 0x28, 0xbf, 0xb1, 0x57, 0xf4, 0xb8, 0x91, 0xd9, 0x31, 0xbf, 0xf9,
	0x89, 0x48, 0xac, 0x11, 0x68, 0x0a, 0x0f, 0xca, 0x2e, 0x3e, 0x15, 0xd1, 0x19, 0x51, 0x97, 0xb6,
	0xad, 0x9a, 0x6a, 0x34, 0x87, 0xa1, 0xe1, 0xf6, 0x95, 0x54, 0xec, 0x82, 0x04, 0xca, 0xdc, 0x85,
	0x3b, 0xdb, 0x6d, 0x38, 0xff, 0xbe, 0x8a, 0xc1, 0x75, 0x13, 0xff, 0x35, 0x0c, 0x6b, 0xfb, 0x7a,
	0x70, 0xb0, 0x90, 0x72, 0xa5, 0x07, 0x47, 0xc1, 0xe0, 0x4a, 0x46, 0x4f, 0x61, 0x18, 0x5c, 0xd2,
	0xe0, 0xda, 0xb0, 0x71, 0xc4, 0xa4, 0xe5, 0xb3, 0xae, 0xf4, 0xff, 0x6d, 0x81, 0xb3, 0xaa, 0x9c,
	0xd5, 0xc0, 0x68, 0x55, 0x06, 0xc6, 0x23, 0xe8, 0xb1, 0x84, 0x44, 0x65, 0xc7, 0x16, 0x02, 0xf2,
	0x60, 0x27, 0x10, 0x49, 0x42, 0x78, 0xe8, 0x75, 0x0c, 0x71, 0xa5, 0xb8, 0xe2, 0xb3, 0x7b, 0x9b,
	0xcf, 0xde, 0x56, 0x3e, 0xf7, 0x00, 0x74, 0xc3, 0x31, 0x1e, 0xe9, 0x88, 0x8b, 0x81, 0x56, 0xd1,
	0x68, 0xbe, 0xcd, 0xf9, 0x67, 0x79, 0x1c, 0x9f, 0x89, 0x98, 0x05, 0x4b, 0x3b, 0xdc, 0x9a, 0x6a,
	0x7f, 0x06, 0xfd, 0xc2, 0xf1, 0xa6, 0xa4, 0xd6, 0xc5, 0xeb, 0xd8, 0x1a, 0xf5, 0xff, 0x6a, 0xc3,
	0xbb, 0xd5, 0xee, 0x47, 0x2f, 0xa0, 0x1b, 0x0b, 0x12, 0x1a, 0x53, 0x77, 0xf6, 0xc9, 0x3d, 0x83,
	0x62, 0x7f, 0x4e, 0x54, 0x70, 0x79, 0x2a, 0x48, 0x88, 0x8d, 0x09, 0x7a, 0x09, 0xfd, 0x62, 0x10,
	0xdb, 0xfe, 0x78, 0xb6, 0xd5, 0xf8, 0xd0, 0xc0, 0xb1, 0x35, 0xd3, 0x43, 0xf1, 0x2a, 0xa5, 0xd1,
	0xeb, 0x9c, 0xc4, 0xfa, 0x7a, 0x3b, 0xe6, 0x5d, 0xa8, 0xaa, 0x34, 0x59, 0x84, 0x73, 0xa1, 0x8a,
	0xa9, 0x69, 0x3b, 0x60, 0xad, 0x19, 0x3f, 0x07, 0xb7, 0xe2, 0x58, 0xc3, 0x43, 0xa2, 0x48, 0x46,
	0xd5, 0x77, 0x61, 0xe6, 0xb5, 0xcc, 0xf5, 0x54, 0x34, 0xe3, 0x27, 0xe0, 0xac, 0x92, 0x40, 0x23,
	0x68, 0xb3, 0xd0, 0x52, 0xd6, 0x66, 0xa1, 0x4f, 0xe0, 0xc1, 0xaa, 0xa3, 0xed, 0xcb, 0xf8, 0x10,
	0x3a, 0x41, 0x9a, 0x97, 0x23, 0x21, 0x48, 0x73, 0xad, 0x49, 0x68, 0x52, 0x36, 0x6e, 0x42, 0x4d,
	0x2b, 0x47, 0x69, 0x6e, 0xfb, 0x56, 0x2f, 0x75, 0xe1, 0x48, 0x6a, 0x06, 0xbb, 0x89, 0x78, 0x88,
	0x4b, 0xd1, 0xff, 0x0d, 0x06, 0xe5, 0x11, 0xe8, 0x40, 0xa3, 0xcc, 0x31, 0x96, 0xfb, 0xbd, 0x4d,
	0xe3, 0xa5, 0x40, 0xe1, 0x12, 0x8e, 0x66, 0xd0, 0x8b, 0x59, 0xc2, 0x94, 0xa5, 0x7d, 0x77, 0x83,
	0xdd, 0xa9, 0xc6, 0xe0, 0x02, 0xea, 0x1f, 0xc3, 0xb0, 0xa6, 0xff, 0x7f, 0xa9, 0xf9, 0x3f, 0x98,
	0x97, 0x0e, 0xd3, 0x2c, 0x15, 0x3c, 0xa3, 0x4d, 0x0a, 0x75, 0xe6, 0x59, 0x1e, 0x04, 0x34, 0xcb,
	0x8c, 0x9b, 0x01, 0x2e, 0x45, 0xfd, 0x26, 0x53, 0x29, 0x93, 0x2c, 0xb2, 0xde, 0xac, 0xe4, 0x4f,
	0x60, 0x74, 0xae, 0x44, 0x5a, 0xf9, 0x8d, 0x34, 0xaf, 0xe5, 0x10, 0x1e, 0x1f, 0x5e, 0x12, 0x1e,
	0xd1, 0x33, 0xfb, 0x5f, 0xd8, 0x00, 0xac, 0x7d, 0x31, 0xda, 0xf5, 0x2f, 0x86, 0xef, 0xc3, 0xc3,
	0x23, 0x1a, 0x53, 0x45, 0xef, 0x39, 0xe8, 0x63, 0x7d, 0xff, 0x32, 0xe7, 0x9b, 0x21, 0xb3, 0x3f,
	0x3a, 0xd0, 0x39, 0x11, 0x0b, 0x74, 0x0c, 0x70, 0xcc, 0xdf, 0xe6, 0x34, 0xd7, 0xfe, 0xd0, 0x07,
	0xb7, 0xeb, 0xde, 0x3a, 0x18, 0x8f, 0xef, 0xda, 0x2a, 0xc8, 0xf3, 0xdf, 0x41, 0x6f, 0x60, 0x54,
	0x4f, 0x0d, 0x3d, 0x6d, 0xbe, 0x78, 0x77, 0x65, 0xbe, 0xc5, 0xeb, 0xd7, 0xb0, 0x63, 0x29, 0x45,
	0xcd, 0xa7, 0xbb, 0x4e, 0xf5, 0x16, 0x3f, 0x27, 0xe0, 0xac, 0x38, 0x43, 0x1f, 0x35, 0xa0, 0x4d,
	0x36, 0xb7, 0xf8, 0xfa, 0x56, 0x17, 0x7e, 0xc1, 0x2d, 0xba, 0x5d, 0xe7, 0x35, 0xd2, 0xef, 0xf7,
	0x34, 0x7f, 0xf0, 0x4b, 0xfd, 0x33, 0xbb, 0xe8, 0x9b, 0x2f, 0xee, 0xe7, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xc1, 0x92, 0x6c, 0xd5, 0xef, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	EnqueueJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ChangePriority(ctx context.Context, in *ChangePriorityRequest, opts ...grpc.CallOption) (*JobResponse, error)
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	RerunJob(ctx context.Context, in *RerunJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) EnqueueJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/serialization.Job/EnqueueJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) ChangePriority(ctx context.Context, in *ChangePriorityRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/serialization.Job/ChangePriority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/serialization.Job/StopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/serialization.Job/DeleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) RerunJob(ctx context.Context, in *RerunJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/serialization.Job/RerunJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	EnqueueJob(context.Context, *JobRequest) (*JobResponse, error)
	ChangePriority(context.Context, *ChangePriorityRequest) (*JobResponse, error)
	StopJob(context.Context, *StopJobRequest) (*JobResponse, error)
	DeleteJob(context.Context, *DeleteJobRequest) (*JobResponse, error)
	RerunJob(context.Context, *RerunJobRequest) (*JobResponse, error)
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_EnqueueJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).EnqueueJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serialization.Job/EnqueueJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).EnqueueJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_ChangePriority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePriorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).ChangePriority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serialization.Job/ChangePriority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).ChangePriority(ctx, req.(*ChangePriorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serialization.Job/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serialization.Job/DeleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_RerunJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerunJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).RerunJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serialization.Job/RerunJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).RerunJob(ctx, req.(*RerunJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serialization.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnqueueJob",
			Handler:    _Job_EnqueueJob_Handler,
		},
		{
			MethodName: "ChangePriority",
			Handler:    _Job_ChangePriority_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _Job_StopJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _Job_DeleteJob_Handler,
		},
		{
			MethodName: "RerunJob",
			Handler:    _Job_RerunJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
